version: '2'

volumes:
    orderer.example.com:

networks:
  atln:

services:
    orderer.example.com:
        container_name: orderer.example.com
        image: hyperledger/fabric-orderer:$IMAGETAG1
        environment:
            # base env
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LOCALMSPID=$LOCALMSPID
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            # TLS
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            # cluster
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            # genesis file           
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            # logging level
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer

        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        volumes:
            - ./../conf/hosts:/etc/hosts
            - ./../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ./../crypto-config/ordererOrganizations/$ORGURL/orderers/$NODENAME/msp:/var/hyperledger/orderer/msp
            - ./../crypto-config/ordererOrganizations/$ORGURL/orderers/$NODENAME/tls:/var/hyperledger/orderer/tls
            - ./../production/$NODENAME:/var/hyperledger/production/orderer
        ports:
          - 7050:7050
        networks:
            - atln

