Organizations:

    - &OrdererA
        Name: OrdererA
        ID: OrdererA
        MSPDir: ./crypto-config/ordererOrganizations/orga.atlchain.com/msp

        Policies: &OrdererAPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrdererA.member', 'OrdererA.admin', 'OrdererA.peer', 'OrdererA.client')" 
            Writers:
                Type: Signature
                Rule: "OR('OrdererA.member', 'OrdererA.admin', 'OrdererA.peer', 'OrdererA.client')" 
            Admins:
                Type: Signature
                Rule: "OR('OrdererA.admin')"

    - &OrdererB
        Name: OrdererB
    
        ID: OrdererB
    
        MSPDir: ./crypto-config/ordererOrganizations/orgb.atlchain.com/msp
    
        Policies: &OrdererBPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrdererB.member', 'OrdererB.admin', 'OrdererB.peer', 'OrdererB.client')" 

            Writers:
                Type: Signature
                Rule: "OR('OrdererB.member', 'OrdererB.admin', 'OrdererB.peer', 'OrdererB.client')" 

            Admins:
                Type: Signature
                Rule: "OR('OrdererB.admin')"
              
    - &OrgA
        Name: OrgA
    
        ID: OrgA
    
        MSPDir: ./crypto-config/peerOrganizations/orga.atlchain.com/msp
    
        Policies: &OrgAPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrgA.admin', 'OrgA.peer', 'OrgA.client', 'OrgA.member')"

            Writers:
                Type: Signature
                Rule: "OR('OrgA.admin', 'OrgA.peer', 'OrgA.client', 'OrgA.member')"

            Admins:
                Type: Signature
                Rule: "OR('OrgA.admin')"
    
        AnchorPeers:
            - Host: peer0.orga.atlchain.com
              Port: 7051
    
    - &OrgB
        Name: OrgB

        ID: OrgB

        MSPDir: ./crypto-config/peerOrganizations/orgb.atlchain.com/msp

        Policies: &OrgBPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrgB.admin', 'OrgB.peer', 'OrgB.client', 'OrgB.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrgB.admin', 'OrgB.peer', 'OrgB.client', 'OrgB.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrgB.admin')"

        AnchorPeers:
            - Host: peer0.orgb.atlchain.com
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    ACLs: &ACLsDefault
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetConfigTree: /Channel/Application/Readers
        cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Readers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers
    Organizations:
    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: kafka
    Addresses:
        - orderer0.orga.atlchain.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0

    Kafka:
        Brokers:
            - kafka.atlchain.com:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    OrdererChannel:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            OrdererType: kafka
            Organizations:
                - <<: *OrdererA
                - <<: *OrdererB
                  Policies:
                      <<: *OrdererAPolicies
                      <<: *OrdererBPolicies
                      Admins:
                          Type: Signature
                          Rule: "OR('OrdererA.admin', 'OrdererB.admin')"
                         
        Consortiums:
            SampleConsortium:
                Organizations:
                    - <<: *OrgA
                    - <<: *OrgB
                      Policies:
                          <<: *OrgAPolicies
                          <<: *OrgBPolicies
                          Admins:
                              Type: Signature
                              Rule: "OR('OrgA.admin', 'OrgB.admin')"
                          
    TxChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - <<: *OrgA
                - <<: *OrgB
