# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: OrdererA
    Domain: orga.atlchain.com
    Specs:
      - Hostname: orderer0

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: OrgA
    Domain: orga.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

