# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: OrdererA
    Domain: orga.atlchain.com
    Specs:
      - Hostname: orderer0

  - Name: OrdererB
    Domain: orgb.atlchain.com
    Specs:
      - Hostname: orderer0

  - Name: OrdererC
    Domain: orgc.atlchain.com
    Specs:
      - Hostname: orderer0

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: OrgA
    Domain: orga.atlchain.com
    EnableNodeOUs: true
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    Template:
      Count: 2
      # Start: 5
    Users:
    # Count: The number of user accounts _in addition_ to Admin
      Count: 2

    # Copy the following example when need more orgs
  - Name: OrgB
    Domain: orgb.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: OrgC
    Domain: orgc.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
