OrdererOrgs:

  - Name: OrdererOrgA
    Domain: orga.atlchain.com
    Specs:
      - Hostname: orderer0

  - Name: OrdererOrgB
    Domain: orgb.atlchain.com
    Specs:
      - Hostname: orderer0

PeerOrgs:

  - Name: OrgA
    Domain: orga.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: OrgB
    Domain: orgb.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
