OrdererOrgs:

  - Name: OrdererOrgA
    Domain: orga.atlchain.com
    Specs:
      - Hostname: orderer0

PeerOrgs:

  - Name: OrgA
    Domain: orga.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: OrgB
    Domain: orgb.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: OrgC
    Domain: orgc.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: OrgD1
    Domain: orgd1.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Org#32
    Domain: org#32.atlchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
