# ca node docker compose file

version: '2'

networks:
    byfn:

services:
    ca0.atlchain.com:
        image: hyperledger/fabric-ca:1.4.0
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-orga
            - FABRIC_CA_SERVER_TLS_ENABLED=false
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.orga.atlchain.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.orga.atlchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ./crypto-config/peerOrganizations/orga.atlchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
            - ../ATLChain_NETWORK/ca-config/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
        container_name: ca0.atlchain.com
        networks:
            - byfn
        ports:
            - 7054:7054
