# peer node docker compose file

version: '2'

networks:
    byfn:

services:
    couchdb0.orga.atlchain.com:
        container_name: couchdb0.orga.atlchain.com
        image: hyperledger/fabric-couchdb:0.4.14
        environment:
            - COUCHDB_USER=
            - COUCHDB_PASSWORD=
        # ports:
        #     - "5984:5984"
        networks:
            - byfn

    peer0.orga.atlchain.com:
        container_name: peer0.orga.atlchain.com
        image: hyperledger/fabric-peer:1.4.0
        environment:
            - CORE_PEER_ID=peer0.orga.atlchain.com
            - CORE_PEER_ADDRESS=127.0.0.1:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=127.0.0.1:7051
            - CORE_PEER_LOCALMSPID=OrgA
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
            - FABRIC_LOGGING_SPEC=INFO
            # enabled TLS
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # CouchDB
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.orga.atlchain.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
        depends_on:
            - couchdb0.orga.atlchain.com
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/orga.atlchain.com/peers/peer0.orga.atlchain.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/orga.atlchain.com/peers/peer0.orga.atlchain.com/tls:/etc/hyperledger/fabric/tls
            - ./production/peer0.orga.atlchain.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        networks:
            - byfn
        ports:
            - 7051:7051
            - 7053:7053
