version: '2'

volumes:
    peer0.orga.atlchain.com:

networks:
    atln:

services:
    peer0.orga.atlchain.com:
        container_name: peer0.orga.atlchain.com
        image: hyperledger/fabric-peer:1.4.0
        environment:
            # peer env
            - CORE_PEER_ID=peer0.orga.atlchain.com
            - CORE_PEER_ADDRESS=${DOCKER_COMPOSE_PEER_ADDRESS}:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=${DOCKER_COMPOSE_PEER_ADDRESS}:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_GOSSIP_BOOTSTRAP=${DOCKER_COMPOSE_PEER_GOSSIP_BOOTSTRAP}:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${DOCKER_COMPOSE_PEER_ADDRESS}:7051
            - CORE_PEER_LOCALMSPID=OrgA
            # state database
            - CORE_LEDGER_STATE_STATEDATABASE= goleveldb # CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
            # basic env
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_atln
            - FABRIC_LOGGING_SPEC=INFO
            # - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/orga.atlchain.com/peers/peer0.orga.atlchain.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/orga.atlchain.com/peers/peer0.orga.atlchain.com/tls:/etc/hyperledger/fabric/tls
            - peer0.orga.atlchain.com:/var/hyperledger/production
        ports:
          - 7051:7051
          - 7052:7052
          - 7053:7053

        networks:
            - atln
