version: '2'

volumes:
    orderer0.orga.atlchain.com:
    peer0.orga.atlchain.com:
    peer1.orga.atlchain.com:
    peer0.orgb.atlchain.com:
    peer1.orgb.atlchain.com:

networks:
    byfn:

services:

    orderer0.orga.atlchain.com:
        extends:
            file:   base/docker-compose-base.yaml
            service: orderer0.orga.atlchain.com
        container_name: orderer0.orga.atlchain.com
        networks:
            - byfn

    peer0.orga.atlchain.com:
        container_name: peer0.orga.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer0.orga.atlchain.com
        networks:
            - byfn

    peer1.orga.atlchain.com:
        container_name: peer1.orga.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer1.orga.atlchain.com
        networks:
            - byfn
    
    peer0.orgb.atlchain.com:
        container_name: peer0.orgb.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer0.orgb.atlchain.com
        networks:
            - byfn
    
    peer1.orgb.atlchain.com:
        container_name: peer1.orgb.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer1.orgb.atlchain.com
        networks:
            - byfn

    cli:
        container_name: cli
        image: hyperledger/fabric-tools:$IMAGE_TAG
        tty: true
        stdin_open: true
        environment:
            - GODEBUG=netdns=go
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            #- FABRIC_LOGGING_SPEC=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.orga.atlchain.com:7051
            - CORE_PEER_LOCALMSPID=OrgA
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.atlchain.com/peers/peer0.orgb.atlchain.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.atlchain.com/peers/peer0.orgb.atlchain.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.atlchain.com/peers/peer0.orga.atlchain.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.atlchain.com/users/Admin@orga.atlchain.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../ATLChain_CC/:/opt/gopath/src/github.com/chaincode
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
            - ../ATLChain_DEMO:/opt/gopath/src/github.com/hyperledger/fabric/peer/demo
        depends_on:
            - orderer0.orga.atlchain.com
            - peer0.orga.atlchain.com
            - peer1.orga.atlchain.com
            - peer0.orgb.atlchain.com
            - peer1.orgb.atlchain.com
        ports:
            - 10001:4444
            - 10002:4000

        networks:
            - byfn
